import { Column, Entity, JoinColumn, OneToOne, PrimaryColumn } from "typeorm";
import { Order } from "./order";

@Entity()
export class PaypalOrder {
  @PrimaryColumn({generated: false})
  public id: string; // generated by paypal

  @OneToOne((type) => Order, (order) => order.paypal, {onDelete: "SET NULL"})
  @JoinColumn()
  public order: Order;

  @Column({type: "decimal", precision: 13, scale: 2})
  public totalPrice: number;

  @Column({nullable: true})
  public captureID: string;
}
